[package]
name = "gym_102906"
version = "0.1.0"
authors = ["Sergei Blinov <blinovsv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name="f_dfs"
path="f_dfs.rs"
